In [6]:
import rasterio
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
import time

# Define the paths to your two raster datasets
path_to_ground_truth = r"C:\Users\User\Documents\CS_sequence_check\kansas_area\KST10_clip_2022.tif"
path_to_predicted = r"C:\Users\User\Documents\CS_sequence_check\kansas_area\kansas_area_predicted_raster.tif"

# Start the timer
start_time = time.time()

# Open the raster datasets using rasterio
with rasterio.open(path_to_ground_truth) as ground_truth_src, rasterio.open(path_to_predicted) as predicted_src:
    # Read the raster data as numpy arrays
    ground_truth_data = ground_truth_src.read(1)
    predicted_data = predicted_src.read(1)

# Ensure the two raster datasets have the same shape
if ground_truth_data.shape != predicted_data.shape:
    raise ValueError("The two raster datasets must have the same dimensions.")

# Flatten the arrays to 1D
ground_truth_flat = ground_truth_data.flatten()

# Replace NaN values in predicted_flat with a specific value (e.g., -1)
predicted_flat = predicted_data.flatten()
predicted_flat[np.isnan(predicted_flat)] = -1  # Replace NaN with -1 or any suitable placeholder

# Create a mask to filter out replaced NaN values (-1)
valid_mask = (predicted_flat != -1)

# Apply masks to filter out NaN values
ground_truth_flat = ground_truth_flat[valid_mask]
predicted_flat = predicted_flat[valid_mask]

# Calculate the confusion matrix
confusion = confusion_matrix(ground_truth_flat, predicted_flat)

# Calculate the accuracy
accuracy = accuracy_score(ground_truth_flat, predicted_flat)

# Calculate the elapsed time
end_time = time.time()
elapsed_time = end_time - start_time

# Print the confusion matrix, accuracy, and elapsed time
print("Confusion Matrix:")
print(confusion)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Elapsed Time: {elapsed_time:.2f} seconds")


Confusion Matrix:
[[ 33088      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0]
 [     0 156531      0  17419      0      0      0  32757      0      0
      47      0      0      0  33406      0    333      0      0      2
       0      0      0     94   1651      0      8   1041      0      0
       0]
 [     0     94      0      5      0      0      0      0      0      0
       0      0      0      0      1      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0]
 [     0  38890      0  40962      0      0      0  22159      0      0
      84      0      0      0  30841      0     26      0      1      4
       0      0      0     28    312      0      0    615      0      0
       0]
 [     0     33      0      2      0      0      0      4      0      0
      

In [7]:
import rasterio
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
import time
# Define the paths to your two raster datasets
path_to_ground_truth = r"C:\Users\User\Documents\CS_sequence_check\kansas_area\KST10_clip_2022.tif"
path_to_predicted = r"C:\Users\User\Documents\CS_sequence_check\kansas_area\KST10_clip_2020.tif"

# Start the timer
start_time = time.time()

# Open the raster datasets using rasterio
with rasterio.open(path_to_ground_truth) as ground_truth_src, rasterio.open(path_to_predicted) as predicted_src:
    # Read the raster data as numpy arrays
    ground_truth_data = ground_truth_src.read(1)
    predicted_data = predicted_src.read(1)

# Ensure the two raster datasets have the same shape
if ground_truth_data.shape != predicted_data.shape:
    raise ValueError("The two raster datasets must have the same dimensions.")

# Flatten the arrays to 1D
ground_truth_flat = ground_truth_data.flatten()

# Replace NaN values in predicted_flat with a specific value (e.g., -1)
predicted_flat = predicted_data.flatten()
predicted_flat[np.isnan(predicted_flat)] = -1  # Replace NaN with -1 or any suitable placeholder

# Create a mask to filter out replaced NaN values (-1)
valid_mask = (predicted_flat != -1)

# Apply masks to filter out NaN values
ground_truth_flat = ground_truth_flat[valid_mask]
predicted_flat = predicted_flat[valid_mask]

# Calculate the confusion matrix
confusion = confusion_matrix(ground_truth_flat, predicted_flat)

# Calculate the accuracy
accuracy = accuracy_score(ground_truth_flat, predicted_flat)

# Calculate the elapsed time
end_time = time.time()
elapsed_time = end_time - start_time

# Print the confusion matrix, accuracy, and elapsed time
print("Confusion Matrix:")
print(confusion)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Elapsed Time: {elapsed_time:.2f} seconds")


C:\Users\User\AppData\Local\Temp\ipykernel_7564\24457718.py:27: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  predicted_flat[np.isnan(predicted_flat)] = -1  # Replace NaN with -1 or any suitable placeholder


Confusion Matrix:
[[ 33088      0      0 ...      0      0      0]
 [     0 114600     16 ...     72    633    810]
 [     0     98      0 ...      0      0      0]
 ...
 [     0   2562      0 ...      1      0      0]
 [     0    331      7 ...     18    133      2]
 [     0    320      0 ...      1      0    509]]
Accuracy: 44.13%
Elapsed Time: 0.52 seconds


In [5]:
import rasterio
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
import time
# Define the paths to your two raster datasets
path_to_ground_truth = r"C:\Users\User\Documents\CS_sequence_check\ohio_area\ohio_clip_2020.tif"
path_to_predicted = r"C:\Users\User\Documents\CS_sequence_check\ohio_area\ohio_area_predicted_raster.tif"

# Start the timer
start_time = time.time()

# Open the raster datasets using rasterio
with rasterio.open(path_to_ground_truth) as ground_truth_src, rasterio.open(path_to_predicted) as predicted_src:
    # Read the raster data as numpy arrays
    ground_truth_data = ground_truth_src.read(1)
    predicted_data = predicted_src.read(1)

# Ensure the two raster datasets have the same shape
if ground_truth_data.shape != predicted_data.shape:
    raise ValueError("The two raster datasets must have the same dimensions.")

# Flatten the arrays to 1D
ground_truth_flat = ground_truth_data.flatten()

# Replace NaN values in predicted_flat with a specific value (e.g., -1)
predicted_flat = predicted_data.flatten()
predicted_flat[np.isnan(predicted_flat)] = -1  # Replace NaN with -1 or any suitable placeholder

# Create a mask to filter out replaced NaN values (-1)
valid_mask = (predicted_flat != -1)

# Apply masks to filter out NaN values
ground_truth_flat = ground_truth_flat[valid_mask]
predicted_flat = predicted_flat[valid_mask]

# Calculate the confusion matrix
confusion = confusion_matrix(ground_truth_flat, predicted_flat)

# Calculate the accuracy
accuracy = accuracy_score(ground_truth_flat, predicted_flat)

# Calculate the elapsed time
end_time = time.time()
elapsed_time = end_time - start_time

# Print the confusion matrix, accuracy, and elapsed time
print("Confusion Matrix:")
print(confusion)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Elapsed Time: {elapsed_time:.2f} seconds")


Confusion Matrix:
[[51829     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0]
 [    0 56532  3149   338   571    53     1     0     0     0     1     0
      0     0     0     0     3     0     0     0    30     0     0     0]
 [    0 17198 49551     0     0   396     0     0     0     0     0    37
     83     0     0     0     0     0     0     0   247     0     0     0]
 [    0  1580  6433     0     0    99    56     0     0     0     0     0
      0     0     0     0     0     0     0     0    34     0     0     0]
 [    0     0   162     1     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0]
 [    0    51   286     0     0  1306    45     0     0     0     0     0
      0     0     0     0     0     0     0     0   227     0     0     0]
 [    0    35    10     0     0    40    34     0     0     0     0     0
      0     0 

In [8]:
################### difference when changing CDL values to crop values ######################################

In [16]:
import rasterio
import numpy as np
import time
from sklearn.metrics import confusion_matrix, accuracy_score
from rasterio.warp import calculate_default_transform, reproject, Resampling


# Start the timer
start_time = time.time()
# Reclassification dictionaries for two rasters (replace with actual data)

non_active = [0,61,63,64,65,82,83,87,88,
                            111,112,121,122,123,124,131,
                            141,142,143,152,176,190,195]
cdl_values = {12: 1, 13: 1, 255: 1, 266: 1, 237: 1, 26: 5, 241:5, 254: 5, 238: 2, 239: 2, 23: 3}
all_values = [0,61,63,64,65,82,83,87,88,
                            111,112,121,122,123,124,131,
                            141,142,143,152,176,190,195,1,5,2,23]
range_min, range_max = 0, 240
# Paths to the original raster files
path_to_original_ground_truth = r"C:\Users\User\Documents\CS_sequence_check\kansas_area\kansas_area_predicted_raster.tif"
path_to_original_predicted = r"C:\Users\User\Documents\CS_sequence_check\ohio_area\ohio_CDL_forecast_clip.tif"

# Open the ground truth raster
with rasterio.open(path_to_original_ground_truth) as src1:
    profile1 = src1.profile

    # Open the predicted raster
    with rasterio.open(path_to_original_predicted) as src2:
        profile2 = src2.profile

        # Determine the desired output profile (e.g., match src1 to src2)
        transform, width, height = calculate_default_transform(
            src1.crs, src2.crs, src2.width, src2.height, *src2.bounds)
        profile1.update({
            'crs': src2.crs,
            'transform': transform,
            'width': width,
            'height': height
        })

        # Reproject and resample src1 to match src2
        with rasterio.open('reprojected_ground_truth.tif', 'w', **profile1) as dst:
            for i in range(1, src1.count + 1):
                reproject(
                    source=rasterio.band(src1, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src1.transform,
                    src_crs=src1.crs,
                    dst_transform=transform,
                    dst_crs=src2.crs,
                    resampling=Resampling.nearest)


# Function to reclassify a raster
def reclassify_raster(input_path, reclass_dict, output_path):
    with rasterio.open(input_path) as src:
        raster = src.read(1)  # Read the first band
        reclassified_raster = np.copy(raster)

        for old_value, new_value in cdl_values.items():
            reclassified_raster[raster == old_value] = new_value
        
        # Apply reclassification
        for value in non_active:
            reclassified_raster[reclassified_raster == value] = 4
        
         # Reclassify the raster
        # Set pixels within the range and not in the exclusion list to 6
        reclassify_mask = np.isin(reclassified_raster, all_values, invert=True) & (reclassified_raster >= range_min) & (reclassified_raster <= range_max)
        reclassified_raster[reclassify_mask] = 6

        new_meta = src.meta
        new_meta.update(dtype=rasterio.int32)

        with rasterio.open(output_path, 'w', **new_meta) as dst:
            dst.write(reclassified_raster, 1)

# Reclassify both rasters
reclassify_raster(path_to_original_ground_truth, cdl_values, 'reclassified_ground_truth.tif')
reclassify_raster(path_to_original_predicted, cdl_values, 'reclassified_predicted.tif')


# Open the reclassified raster datasets using rasterio
with rasterio.open('reclassified_ground_truth.tif') as ground_truth_src, rasterio.open('reclassified_predicted.tif') as predicted_src:
    # Read the raster data as numpy arrays
    ground_truth_data = ground_truth_src.read(1)
    predicted_data = predicted_src.read(1)

# Ensure the two raster datasets have the same shape
if ground_truth_data.shape != predicted_data.shape:
    raise ValueError("The two raster datasets must have the same dimensions.")

# Flatten the arrays to 1D
ground_truth_flat = ground_truth_data.flatten()
predicted_flat = predicted_data.flatten()
predicted_flat[np.isnan(predicted_flat)] = -1  # Replace NaN with -1 or any suitable placeholder

# Create a mask to filter out replaced NaN values (-1)
valid_mask = (predicted_flat != -1)

# Apply masks to filter out NaN values
ground_truth_flat = ground_truth_flat[valid_mask]
predicted_flat = predicted_flat[valid_mask]

# Calculate the confusion matrix and accuracy
confusion = confusion_matrix(ground_truth_flat, predicted_flat)
accuracy = accuracy_score(ground_truth_flat, predicted_flat)

# Calculate the elapsed time
end_time = time.time()
elapsed_time = end_time - start_time

# Print the confusion matrix, accuracy, and elapsed time
print("Confusion Matrix:")
print(confusion)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Elapsed Time: {elapsed_time:.2f} seconds")


ValueError: The two raster datasets must have the same dimensions.